# Generated by Django 5.2.2 on 2025-06-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_lesson_homework_homework_homeworkfile'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='class',
            name='Class_year_admission_checkConstraint',
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.CheckConstraint(condition=models.Q(('year_admission__gte', 2022), ('year_admission__lte', 2225)), name='Class_year_admission_checkConstraint'),
        ),
    ]
