# Generated by Django 5.2.2 on 2025-06-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_remove_user_login_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='homework',
        ),
    ]
