# Generated by Django 5.2.2 on 2025-06-15 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_marktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='mark_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diary.marktype'),
        ),
        migrations.AddField(
            model_name='mark',
            name='quarter_number',
            field=models.IntegerField(default=4),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.CheckConstraint(condition=models.Q(('quarter_number__gte', 1), ('quarter_number__lte', 4)), name='Quarter_number_checkConstraint'),
        ),
    ]
