# Generated by Django 5.2.2 on 2025-06-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_mark_mark_type_mark_quarter_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='quarter_number',
            field=models.IntegerField(default=4),
        ),
    ]
