# Generated by Django 5.2.2 on 2025-06-15 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_lesson_quarter_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('year', models.IntegerField()),
                ('quarter_number', models.IntegerField(blank=True, null=True)),
                ('mark_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.marktype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.subject')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('mark__gte', 2), ('mark__lte', 5)), name='FinalMark_checkConstraint')],
            },
        ),
    ]
